name: deploy.yml
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          request_pty: true
          script_stop: true
          key: ${{ secrets.KEY }}
          script: |
            # Become the tool account
            become ukbot

            # Update from GitHub repo.
            git pull

            # Activate the virtual environment and update dependencies
            source www/python/venv/bin/activate
            pip install -U pip wheel
            pip install -e . --upgrade

            # Load any changes to jobs.yaml
            toolforge-jobs load jobs.yaml

            # Restart the webservice
            webservice restart
